name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from (usually 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu machine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your code from the repository
      
    - name: Setup GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch to deploy to
        folder: .  # The folder containing your HTML files (use '.' for the root)
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided token by GitHub

